# Generated by Django 2.1.1 on 2021-03-03 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Photo', models.BooleanField(default=True)),
                ('answer_content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_html',
        ),
        migrations.AddField(
            model_name='question',
            name='is_MCQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_answers',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examPortalApp.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examPortalApp.Team'),
        ),
    ]
