# Generated by Django 2.1.1 on 2021-05-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='team',
        #     name='proctor_user',
        # ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
