# Generated by Django 2.1.1 on 2021-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='extra_time',
            field=models.IntegerField(default=0),
        ),
    ]
