# Generated by Django 3.0.8 on 2021-01-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_set',
            new_name='passwordSet',
        ),
    ]
