# Generated by Django 2.1.1 on 2021-03-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0002_auto_20210303_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_Photo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_MCQ',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(default='s', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='s', max_length=2),
        ),
    ]
