# Generated by Django 2.1.1 on 2021-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0002_team_extra_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
