# Generated by Django 2.1.1 on 2021-05-11 12:43

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0002_auto_20210511_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='participant', max_length=30),
        ),
        migrations.AddField(
            model_name='team',
            name='proctor_user',
            field=models.ForeignKey(default=None, null=True, on_delete=models.deletion.SET_NULL, related_name='proctored_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
