# Generated by Django 3.0.8 on 2021-01-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0002_auto_20210125_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_start', models.DateTimeField()),
                ('test_end', models.DateTimeField()),
            ],
        ),
    ]
