# Generated by Django 2.1.1 on 2021-03-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0003_auto_20210304_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_instance',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='team',
            new_name='team_instance',
        ),
    ]
