# Generated by Django 2.1.1 on 2021-05-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0003_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ended_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='entered_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='started_test',
            field=models.BooleanField(default=False),
        ),
    ]
