# Generated by Django 2.1.1 on 2021-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0003_auto_20210406_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marks',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='max_marks',
            field=models.IntegerField(default=2),
        ),
    ]
