# Generated by Django 2.1.1 on 2021-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0004_auto_20210523_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entered_video_call',
            field=models.BooleanField(default=False),
        ),
    ]
