# Generated by Django 2.1.1 on 2021-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0004_auto_20210419_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='marks',
            field=models.FloatField(default=-1),
        ),
    ]
