# Generated by Django 2.1.1 on 2021-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0005_auto_20210420_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
