# Generated by Django 3.1.5 on 2021-01-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0005_auto_20210129_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='folder_id',
        ),
        migrations.AddField(
            model_name='question',
            name='question_subject',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='b_folder_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='c_folder_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='m_folder_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='p_folder_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
