# Generated by Django 2.1.1 on 2021-06-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0005_user_entered_video_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
