# Generated by Django 2.1.1 on 2021-03-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0006_remove_answer_answer_typed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_filename', models.TextField()),
                ('page_no', models.IntegerField()),
                ('answer_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examPortalApp.Answer')),
            ],
        ),
    ]
