# Generated by Django 2.1.1 on 2021-05-01 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0006_answer_graded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_number', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatlog_start', models.IntegerField(default=0)),
                ('team_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examPortalApp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Fishylog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_opentime', models.DateTimeField()),
                ('actionCommited', models.TextField()),
                ('popup_closetime', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatlog',
            name='chatroom_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examPortalApp.ChatRoom'),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='user_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
