# Generated by Django 2.1.1 on 2021-05-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0006_answer_graded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fishylog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('popup_opentime', models.DateTimeField()),
                ('actionCommited', models.TextField()),
                ('popup_closetime', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
