# Generated by Django 2.1.1 on 2021-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0007_answerfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answers',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
