# Generated by Django 2.1.1 on 2021-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortalApp', '0007_auto_20210501_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='participant', max_length=30),
        ),
    ]
